name: hannanhakim
favicon: null
layout_spectrum: 0.3144165724515915
typography_spectrum: 0.8569890270009637
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4245306809898466
  lightness: 0.5121960295364261
  saturation: 0.9344492831733078
  rhythmicContrast: 0.24271023855544627
purpose: []
