typography_spectrum: 0.8016
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.29395
analytics:
  google: null
  facebook: null
  twitter: null
name: hannanhakim
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
